POST http://localhost:3000/bookmark HTTP/1.1
content-type: application/json

{
    "url": "https://google.com",
    "title": "Google",
    "summary": "",
    "tags": ["search"],
    "group": "search engine"
}

###
PUT http://localhost:3000/bookmark/6381c7729c536d5e22f96745 HTTP/1.1
content-type: application/json

{
    "url": "https://naver.com",
    "title": "Naver",
    "summary": "updated",
    "tags": ["search"],
    "group": "search engine"
}

###
DELETE http://localhost:3000/bookmark/6380ea3458bc53ecb8767934 HTTP/1.1

###
// getBookmarkById(id: string)
GET http://localhost:3000/bookmark/6381c7729c536d5e22f96745 HTTP/1.1

###
// getBookmarksByTag(tag: string)
GET http://localhost:3000/bookmarks/tag?names=search HTTP/1.1

###
// getTags()
GET http://localhost:3000/bookmark/tags HTTP/1.1


###
// getBookmarksByGroup(group: string)
GET http://localhost:3000/bookmarks/group?name=search engine HTTP/1.1