version: "3.8"
services:
  bookmark-manager:
    container_name: app-dev
    image: "mcr.microsoft.com/vscode/devcontainers/typescript-node:18-bullseye"
    tty: true
    volumes:
      - ..:/workspace:cached
  postgres:
    container_name: app-dev-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: capstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
