version: "3.8"
services:
  bookmark-manager:
    container_name: app-dev
    image: "mcr.microsoft.com/vscode/devcontainers/typescript-node:18-bullseye"
    tty: true
    volumes:
      - ..:/workspace:cached
  # mongo:
  #   container_name: app-dev-db
  #   image: mongo:6.0.2-focal
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=capstone
